# coding=utf-8
"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
from settings import APP_VERSION
from setuptools import setup

APP = ['app.py']
APP_NAME = 'Hyrax'
VERSION = APP_VERSION
COPYRIGHT = u"Copyright © 2016, Rurouni, All Rights Reserved"

DATA_FILES = []
OPTIONS = {
    'iconfile': 'resources/img/icn.icns',
    'argv_emulation': True,
    'packages': ['resources', 'scripts'],
    'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': "Cloud connected typesetting",
        'CFBundleIdentifier': "com.rurouni.macOS.hyrax",
        'CFBundleVersion': VERSION,
        'CFBundleShortVersionString': VERSION,
        'NSHumanReadableCopyright': COPYRIGHT
    }
}
setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
